### ISSUE TITLE
The name may not be well received in the French community

### ISSUE THREAD

**Issue by yannicka** [fiatjaf/branle#3]
The word "branle" in French is a form of the verb "branler" which can means "masturbate"/"wank".

I know it's hard to find a name for a software, but I think it's better to change it because it could be detrimental.

**Comment by fiatjaf** [comment]
Sorry, but I won't do anything for now. I think someone can host this same codebase but with a different name so French people can use it.

But it is not true that it means only that in French, it has other meanings. It will be good if French users learn about these meanings because of this software, right?

Anyway I can still change the name later, no big deal I guess.
